---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.php-redis: regex:^staging.*
  name: frontend
  namespace: staging
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: php-redis
      containers:
      - image: docker.io/swinton/gb-frontend:staging-b47a15b0c43716efa42a833c3097226e63dfbb4c
        name: php-redis
