---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.php-redis: regex:^staging.*
  name: frontend
  namespace: staging
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: php-redis
      containers:
      - image: docker.io/swinton/gb-frontend:staging-d77ab630ebf112deca8b3f2e3b984fedc22d95d0
        name: php-redis
