name: Build

on: 
  push:
    branches: [master]
  pull_request:
    branches: [master]
  repository_dispatch:
    types: [build]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build ./app --file ./app/Dockerfile --tag gb-frontend:$(date +%s)
